/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.atendente;

import controller.AtendenteController;
import funcoes.*;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import model.Atendente;

/**
 *
 * @author picle
 */
public class EditarAtendente extends javax.swing.JInternalFrame {

    Funcoes funcoes = new Funcoes();
    Atendente atendente = new Atendente();
    FuncoesComboBox funcoesCB = new FuncoesComboBox();
    MascarasDeCampos mascara = new MascarasDeCampos();
    int idAtendente;
    AtendenteController atendenteController = new AtendenteController();
    ResultSet resultAtendente;
    String tipo_telefone, usuarioVelho;

    /**
     * Creates new form EditarAtendente
     */
    public EditarAtendente() {
        initComponents();

        funcoesCB.populaComboBox(atendente, cbSelectAtendente);

        cbSelectAtendente.removeActionListener(cbSelectAtendente.getActionListeners()[0]);

        cbSelectAtendente.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                for (Component c : jPanel1.getComponents()) {
                    if (c instanceof JTextField || c instanceof JRadioButton) {
                        c.setEnabled(true);
                    }
                }

                if (cbSelectAtendente.getSelectedItem() != null) {
                    resultAtendente = atendenteController.selectAllFromAtendenteByUsuario(cbSelectAtendente.getSelectedItem().toString());
                }

                try {

                    if (resultAtendente != null && resultAtendente.next()) {
                        txtUsuario.setText(resultAtendente.getString("usuario"));
                        txtNome.setText(resultAtendente.getString("nome"));
                        txtCpf.setText(resultAtendente.getString("cpf"));

                        if (resultAtendente.getString("tipo_telefone") != null) {
                            if (resultAtendente.getString("tipo_telefone").equals("Celular")) {
                                radioCelular.setSelected(true);
                                mascara.mascaraCelular(txtTelefone);
                            } else if (resultAtendente.getString("tipo_telefone").equals("Fixo")) {
                                radioFixo.setSelected(true);
                                mascara.mascaraTelefoneFixo(txtTelefone);
                            } else if (resultAtendente.getString("tipo_telefone").equals("")) {
                                radioCelular.setSelected(false);
                                radioFixo.setSelected(false);
                            }
                        }

                        txtTelefone.setText(resultAtendente.getString("telefone"));

                        idAtendente = resultAtendente.getInt("id");
                    }
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnEditar = new customSwingComponents.JButtonCadastrar();
        txtCpf = new javax.swing.JFormattedTextField();
        lblCpf = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        lblTelefone = new javax.swing.JLabel();
        radioFixo = new javax.swing.JRadioButton();
        radioCelular = new javax.swing.JRadioButton();
        cbSelectAtendente = new org.jdesktop.swingx.JXComboBox();
        lblSelectAtendente = new javax.swing.JLabel();

        buttonGroup1.add(radioCelular);
        buttonGroup1.add(radioFixo);

        setClosable(true);
        setTitle("Clínica Veterinária - Editar Atendentes");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/group_edit.png"))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/group_edit.png"))); // NOI18N
        lblTitulo.setText("Editar atendentes");

        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuario.setText("Usuário:");

        txtUsuario.setEnabled(false);
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNome.setText("Nome:");

        txtNome.setEnabled(false);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        btnEditar.setText("Salvar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setEnabled(false);
        txtCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCpfFocusGained(evt);
            }
        });

        lblCpf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCpf.setText("CPF:");

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setEnabled(false);

        lblTelefone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelefone.setText("Telefone:");

        radioFixo.setText("Fixo");
        radioFixo.setEnabled(false);
        radioFixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFixoActionPerformed(evt);
            }
        });

        radioCelular.setText("Celular");
        radioCelular.setEnabled(false);
        radioCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCelularActionPerformed(evt);
            }
        });

        cbSelectAtendente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSelectAtendenteItemStateChanged(evt);
            }
        });
        cbSelectAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSelectAtendenteActionPerformed(evt);
            }
        });

        lblSelectAtendente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSelectAtendente.setText("Selecione o atendente:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefone, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCpf, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(radioFixo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioCelular)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtCpf)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome))
                        .addGap(119, 119, 119))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSelectAtendente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSelectAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTitulo)
                                .addGap(61, 61, 61)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblTitulo)
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblSelectAtendente)
                    .addComponent(cbSelectAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioFixo)
                    .addComponent(radioCelular))
                .addGap(18, 18, 18)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtUsuario.setDocument( new LimitNumberCharacters(20) );
        txtNome.setDocument( new LimitNumberCharacters(50) );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        AtendenteController atendenteController = new AtendenteController();

        String usuario = txtUsuario.getText();
        String nome = txtNome.getText();
        String cpf = txtCpf.getText();
        String telefone = txtTelefone.getText();
        usuarioVelho = cbSelectAtendente.getSelectedItem().toString();

        if (radioCelular.isSelected() == true) {
            tipo_telefone = "Celular";
        } else if (radioFixo.isSelected() == true) {
            tipo_telefone = "Fixo";
        }

        Atendente atendente = new Atendente(usuario, cpf, nome, cpf, telefone, tipo_telefone);

        if (atendenteController.editarAtendente(atendente, usuarioVelho)) {
            cbSelectAtendente.removeActionListener(cbSelectAtendente.getActionListeners()[0]);

            funcoes.resetFields(jPanel1);
            funcoes.uncheckRadioButtonGroup(buttonGroup1);
            funcoes.disableFields(jPanel1);
            funcoesCB.populaComboBox(atendente, cbSelectAtendente);

            cbSelectAtendente.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {

                    for (Component c : jPanel1.getComponents()) {
                        if (c instanceof JTextField || c instanceof JRadioButton) {
                            c.setEnabled(true);
                        }
                    }

                    if (cbSelectAtendente.getSelectedItem() != null) {
                        resultAtendente = atendenteController.selectAllFromAtendenteByUsuario(cbSelectAtendente.getSelectedItem().toString());
                    }

                    try {

                        if (resultAtendente != null && resultAtendente.next()) {
                            txtUsuario.setText(resultAtendente.getString("usuario"));
                            txtNome.setText(resultAtendente.getString("nome"));
                            txtCpf.setText(resultAtendente.getString("cpf"));

                            if (resultAtendente.getString("tipo_telefone").equals("Celular")) {
                                radioCelular.setSelected(true);
                                mascara.mascaraCelular(txtTelefone);
                            } else if (resultAtendente.getString("tipo_telefone").equals("Fixo")) {
                                radioFixo.setSelected(true);
                                mascara.mascaraTelefoneFixo(txtTelefone);
                            } else if (resultAtendente.getString("tipo_telefone").equals("")) {
                                radioCelular.setSelected(false);
                                radioFixo.setSelected(false);
                            }

                            txtTelefone.setText(resultAtendente.getString("telefone"));

                            idAtendente = resultAtendente.getInt("id");
                        }
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                }
            });
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpfFocusGained
        // TODO add your handling code here:
        txtCpf.setCaretPosition(0);
        mascara.mascaraCpf(txtCpf);
    }//GEN-LAST:event_txtCpfFocusGained

    private void radioFixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFixoActionPerformed
        // TODO add your handling code here:
        mascara.mascaraTelefoneFixo(txtTelefone);
    }//GEN-LAST:event_radioFixoActionPerformed

    private void radioCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCelularActionPerformed
        // TODO add your handling code here:
        mascara.mascaraCelular(txtTelefone);
    }//GEN-LAST:event_radioCelularActionPerformed

    private void cbSelectAtendenteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSelectAtendenteItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSelectAtendenteItemStateChanged

    private void cbSelectAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSelectAtendenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSelectAtendenteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private customSwingComponents.JButtonCadastrar btnEditar;
    private javax.swing.ButtonGroup buttonGroup1;
    private org.jdesktop.swingx.JXComboBox cbSelectAnimal;
    private org.jdesktop.swingx.JXComboBox cbSelectAnimal1;
    private org.jdesktop.swingx.JXComboBox cbSelectAtendente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSelectAtendente;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JRadioButton radioCelular;
    private javax.swing.JRadioButton radioFixo;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
