/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.atendente;

import controller.AtendenteController;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.Atendente;

/**
 *
 * @author lukas
 */
public class ListarAtendentes extends javax.swing.JInternalFrame {

    Atendente atendente = new Atendente();
    AtendenteController atendenteController = new AtendenteController();
    ArrayList<Atendente> listaAtendente = new ArrayList<>();

    /**
     * Creates new form getAtendentes
     */
    public ListarAtendentes() {
        initComponents();

        String colunas[] = {"Nome", "Usuário", "CPF", "Telefone"};
        Object[][] data = {};
        DefaultTableModel modelo = new DefaultTableModel(data, colunas);
        jTable1.setModel(modelo);
        jTable1.setAutoCreateRowSorter(true);

        listaAtendente = atendenteController.pegarAtendentes(atendente);

        for (Atendente a : listaAtendente) {
            modelo.addRow(new Object[]{
                a.getNome(),
                a.getUsuario(),
                a.getCpf(),
                a.getTelefone()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setTitle("Clínica Veterinária - Todos os Atendentes");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book_open.png"))); // NOI18N

        jTable1.setModel(jTable1.getModel());
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Title 1");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Title 2");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Title 3");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Title 4");
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
