/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.consulta;

import controller.ConsultaController;
import funcoes.*;
import java.time.ZoneId;
import javax.swing.JDesktopPane;
import model.Animal;
import model.Cliente;
import model.Consulta;
import model.Veterinario;
import view.animal.CadastrarAnimal;
import view.cliente.CadastrarCliente;
import view.veterinario.CadastrarVeterinario;

/**
 *
 * @author kairos-04
 */
public class CadastrarConsulta extends javax.swing.JInternalFrame {

    FuncoesComboBox funcoesCB = new FuncoesComboBox();
    Cliente cliente = new Cliente();
    Veterinario veterinario = new Veterinario();
    Animal animal = new Animal();
    JDesktopPane jDesktopPane1;

    /**
     * Creates new form CadastrarConsulta
     */
    public CadastrarConsulta(JDesktopPane jDpane1) {
        initComponents();

        jDesktopPane1 = jDpane1;

        funcoesCB.populaComboBox(cliente, cbDono);
        funcoesCB.populaComboBox(veterinario, cbVeterinario);
        cbAnimal.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnForm = new javax.swing.JPanel();
        lblDescricao = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lblDataConsulta = new javax.swing.JLabel();
        lblDataPrevista = new javax.swing.JLabel();
        lblAnimal = new javax.swing.JLabel();
        lblVeterinario = new javax.swing.JLabel();
        lblDono = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        pickerDtPrevista = new org.jdesktop.swingx.JXDatePicker();
        pickerDtConsulta = new org.jdesktop.swingx.JXDatePicker();
        cbDono = new org.jdesktop.swingx.JXComboBox();
        cbAnimal = new org.jdesktop.swingx.JXComboBox();
        cbVeterinario = new org.jdesktop.swingx.JXComboBox();
        btnAddAnimal = new javax.swing.JButton();
        btnRefreshAnimal = new javax.swing.JButton();
        btnAddDono = new javax.swing.JButton();
        btnRefreshDono = new javax.swing.JButton();
        btnAddVeterinario = new javax.swing.JButton();
        btnRefreshVeterinario = new javax.swing.JButton();
        btnCadastrar = new customSwingComponents.JButtonCadastrar();
        txtValor = new javax.swing.JTextField();

        setBorder(null);
        setClosable(true);
        setTitle("Clínica Veterinária - Cadastrar Consultas");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calendar_add.png"))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calendar_add.png"))); // NOI18N
        lblTitulo.setText("Nova Consulta");

        javax.swing.GroupLayout pnTituloLayout = new javax.swing.GroupLayout(pnTitulo);
        pnTitulo.setLayout(pnTituloLayout);
        pnTituloLayout.setHorizontalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTituloLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnTituloLayout.setVerticalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblDescricao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDescricao.setText("Descrição:");

        lblValor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValor.setText("Valor:");

        lblDataConsulta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDataConsulta.setText("Data da consulta:");

        lblDataPrevista.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDataPrevista.setText("Data prevista:");

        lblAnimal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAnimal.setText("Animal:");

        lblVeterinario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVeterinario.setText("Veterinário:");

        lblDono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDono.setText("Dono:");

        txtDesc.setColumns(20);
        txtDesc.setLineWrap(true);
        txtDesc.setRows(2);
        txtDesc.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDesc);
        txtDesc.setDocument( new LimitNumberCharacters(255) );

        cbDono.setEnabled(false);
        cbDono.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDonoItemStateChanged(evt);
            }
        });
        cbDono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbDonoFocusLost(evt);
            }
        });
        cbDono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDonoActionPerformed(evt);
            }
        });
        cbDono.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbDonoPropertyChange(evt);
            }
        });

        cbAnimal.setEnabled(false);

        cbVeterinario.setEnabled(false);

        btnAddAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        btnAddAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAnimalActionPerformed(evt);
            }
        });

        btnRefreshAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow_refresh.png"))); // NOI18N
        btnRefreshAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshAnimalActionPerformed(evt);
            }
        });

        btnAddDono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        btnAddDono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDonoActionPerformed(evt);
            }
        });

        btnRefreshDono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow_refresh.png"))); // NOI18N
        btnRefreshDono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshDonoActionPerformed(evt);
            }
        });

        btnAddVeterinario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        btnAddVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVeterinarioActionPerformed(evt);
            }
        });

        btnRefreshVeterinario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow_refresh.png"))); // NOI18N
        btnRefreshVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshVeterinarioActionPerformed(evt);
            }
        });

        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnFormLayout = new javax.swing.GroupLayout(pnForm);
        pnForm.setLayout(pnFormLayout);
        pnFormLayout.setHorizontalGroup(
            pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFormLayout.createSequentialGroup()
                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnFormLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnFormLayout.createSequentialGroup()
                                .addComponent(lblAnimal)
                                .addGap(18, 18, 18)
                                .addComponent(cbAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRefreshAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnFormLayout.createSequentialGroup()
                                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVeterinario)
                                    .addComponent(lblDono)
                                    .addComponent(lblDescricao)
                                    .addComponent(lblValor)
                                    .addComponent(lblDataConsulta)
                                    .addComponent(lblDataPrevista))
                                .addGap(18, 18, 18)
                                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pickerDtPrevista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbDono, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(cbVeterinario, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(pickerDtConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtValor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnFormLayout.createSequentialGroup()
                                        .addComponent(btnAddDono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRefreshDono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnFormLayout.createSequentialGroup()
                                        .addComponent(btnAddVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRefreshVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(pnFormLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pnFormLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAnimal, lblDataConsulta, lblDataPrevista, lblDescricao, lblDono, lblValor, lblVeterinario});

        pnFormLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbAnimal, cbDono, cbVeterinario, jScrollPane1, pickerDtPrevista});

        pnFormLayout.setVerticalGroup(
            pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataConsulta)
                    .addComponent(pickerDtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataPrevista)
                    .addComponent(pickerDtPrevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnAddDono)
                    .addComponent(btnRefreshDono)
                    .addComponent(cbDono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblAnimal)
                    .addComponent(cbAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddAnimal)
                    .addComponent(btnRefreshAnimal))
                .addGap(16, 16, 16)
                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnAddVeterinario)
                    .addComponent(btnRefreshVeterinario)
                    .addComponent(cbVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVeterinario))
                .addGap(18, 18, 18)
                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescricao)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbDonoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDonoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDonoItemStateChanged

    private void cbDonoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbDonoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDonoPropertyChange

    private void cbDonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbDonoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDonoFocusLost

    private void cbDonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDonoActionPerformed
        // TODO add your handling code here:
        if (cbDono.getSelectedItem() != null) {
            int idDono = cliente.getClienteIdByNome(cbDono.getSelectedItem().toString());
            funcoesCB.populaComboBox(animal, idDono, cbAnimal);
            cbAnimal.setEnabled(true);
        }

    }//GEN-LAST:event_cbDonoActionPerformed

    private void btnAddAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAnimalActionPerformed
        // TODO add your handling code here:
        CadastrarAnimal cadAnimalView = new CadastrarAnimal(jDesktopPane1);
        jDesktopPane1.add(cadAnimalView);
        cadAnimalView.setVisible(true);
    }//GEN-LAST:event_btnAddAnimalActionPerformed

    private void btnRefreshAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshAnimalActionPerformed
        // TODO add your handling code here:
        if (cbDono.getSelectedItem() != null) {
            int idDono = cliente.getClienteIdByNome(cbDono.getSelectedItem().toString());
            funcoesCB.populaComboBox(animal, idDono, cbAnimal);
            cbAnimal.setEnabled(true);
        }
    }//GEN-LAST:event_btnRefreshAnimalActionPerformed

    private void btnAddDonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDonoActionPerformed
        // TODO add your handling code here:
        CadastrarCliente cadClienteView = new CadastrarCliente();
        jDesktopPane1.add(cadClienteView);
        cadClienteView.setVisible(true);
    }//GEN-LAST:event_btnAddDonoActionPerformed

    private void btnRefreshDonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshDonoActionPerformed
        // TODO add your handling code here:
        funcoesCB.populaComboBox(cliente, cbDono);
    }//GEN-LAST:event_btnRefreshDonoActionPerformed

    private void btnAddVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVeterinarioActionPerformed
        // TODO add your handling code here:
        CadastrarVeterinario cadVetView = new CadastrarVeterinario();
        jDesktopPane1.add(cadVetView);
        cadVetView.setVisible(true);
    }//GEN-LAST:event_btnAddVeterinarioActionPerformed

    private void btnRefreshVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshVeterinarioActionPerformed
        // TODO add your handling code here:
        funcoesCB.populaComboBox(veterinario, cbVeterinario);
    }//GEN-LAST:event_btnRefreshVeterinarioActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        ConsultaController controller = new ConsultaController();
        String dataConsulta = pickerDtConsulta.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate().toString();
        String dataPrevista = pickerDtPrevista.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate().toString();
        String descricao = txtDesc.getText();
        double valor = Double.parseDouble(txtValor.getText());

        Consulta consulta = new Consulta(descricao, valor, dataConsulta, dataPrevista);

        String nomeAnimal = cbAnimal.getSelectedItem().toString();
        String nomeVeterinario = cbVeterinario.getSelectedItem().toString();

        controller.cadastrarConstulta(consulta, nomeAnimal, "admin", nomeVeterinario); // vai cadastrar como se o atendente fosse admin por enquanto, depois vou mudar isso
    }//GEN-LAST:event_btnCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAnimal;
    private javax.swing.JButton btnAddDono;
    private javax.swing.JButton btnAddVeterinario;
    private customSwingComponents.JButtonCadastrar btnCadastrar;
    private javax.swing.JButton btnRefreshAnimal;
    private javax.swing.JButton btnRefreshDono;
    private javax.swing.JButton btnRefreshVeterinario;
    private org.jdesktop.swingx.JXComboBox cbAnimal;
    private org.jdesktop.swingx.JXComboBox cbDono;
    private org.jdesktop.swingx.JXComboBox cbVeterinario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnimal;
    private javax.swing.JLabel lblDataConsulta;
    private javax.swing.JLabel lblDataPrevista;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblVeterinario;
    private org.jdesktop.swingx.JXDatePicker pickerDtConsulta;
    private org.jdesktop.swingx.JXDatePicker pickerDtPrevista;
    private javax.swing.JPanel pnForm;
    private javax.swing.JPanel pnTitulo;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
