/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.consulta;

import controller.AnimalController;
import controller.AtendenteController;
import model.Consulta;
import controller.ConsultaController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.*;
import model.Animal;

/**
 *
 * @author picle
 */
public class ListarConsultas extends javax.swing.JInternalFrame {

    Consulta consulta = new Consulta();
    ConsultaController consultaController = new ConsultaController();
    ArrayList<Consulta> listaConsultas = new ArrayList<>();
    String nomeAtendente, nomeAnimal;
    
    /**
     * Creates new form ListarConsultas
     */
    public ListarConsultas() {
        initComponents();
        
        //criando a table e suas colunas, iniciando com os dados vazios para adicionar com o que vem do banco
        String colunas[] = {"Descrição", "Valor", "Data Consulta", "Data Prevista", "Data Agendamento", "Animal" , "Atendente"}; 
        Object[][] data = { }; // inicializa vazio pois os dados virão do banco
        DefaultTableModel modelo = new DefaultTableModel(data, colunas); // criando modelo com as colunas para colocar na table
        jTable1.setModel(modelo); //colocando o modelo na table
        
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN); //desativa tamanho automatico das colunas
        jTable1.getColumnModel().getColumn(0).setMinWidth(150); // seta tamanho das colunas
        jTable1.getColumnModel().getColumn(0).setMaxWidth(150);
        jTable1.getColumnModel().getColumn(1).setMinWidth(100);
        jTable1.getColumnModel().getColumn(1).setMaxWidth(100);
        jTable1.getColumnModel().getColumn(2).setMinWidth(100);
        jTable1.getColumnModel().getColumn(2).setMaxWidth(100);
        
        jTable1.setAutoCreateRowSorter(true); //metodo que cria ordenador dos dados da table
        
        listaConsultas = consultaController.pegarConsultas(consulta); // metodo que vai chamar o controller > model e vai pegar os dados do banco e retornar em forma de arraylist
        AtendenteController atendenteControllerObj = new AtendenteController();
        AnimalController animalControllerObj = new AnimalController();
        
        for (Consulta c : listaConsultas) { // para cada cliente no arraylist cria uma linha na table
            nomeAtendente = atendenteControllerObj.getAtendenteNomeById(c.getFk_atendente());
            nomeAnimal = animalControllerObj.getAnimalNomeById(c.getFk_animal());
            
            modelo.addRow(new Object[]{
                c.getDescricao(),
                c.getValor(),
                c.getData_consulta(),
                c.getData_prevista(),
                c.getData_agendamento(),
                nomeAnimal,
                nomeAtendente
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setTitle("Clínica Veterinária - Todas as Consultas");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book_open.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(695, 379));

        jTable1.setModel(jTable1.getModel());
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
