/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.animal;

import controller.AnimalController;
import controller.ClienteController;
import funcoes.*;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;
import model.Animal;
import model.Cliente;
import model.ClienteAnimal;
import org.jdesktop.swingx.JXComboBox;
import view.cliente.CadastrarCliente;

/**
 *
 * @author picle
 */
public class EditarAnimal extends javax.swing.JInternalFrame {

    JDesktopPane jDesktopPane1;
    FuncoesComboBox funcoesCB = new FuncoesComboBox();
    Cliente cliente = new Cliente();
    ClienteController clienteControllerObj = new ClienteController();
    Animal animal = new Animal();
    ClienteAnimal clienteAnimalObj = new ClienteAnimal();
    ResultSet resultAnimal;
    AnimalController animalController = new AnimalController();
    int idAnimal, idDono, indexItemCpfDono;
    String cpfDono;

    /**
     * Creates new form EditarAnimal
     */
    public EditarAnimal(JDesktopPane jDpanel) {
        initComponents();

        jDesktopPane1 = jDpanel;

        funcoesCB.populaComboBoxAnimalComId(animal, cbSelectAnimal);

        cbSelectAnimal.removeActionListener(cbSelectAnimal.getActionListeners()[0]);

        cbSelectAnimal.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                for (Component c : pnForm.getComponents()) {
                    if (c instanceof JTextField) {
                        c.setEnabled(true);
                    } else if (c instanceof JSpinner) {
                        c.setEnabled(true);
                    }
                }

                if (cbSelectAnimal.getSelectedItem() != null) {
                    String partes[] = cbSelectAnimal.getSelectedItem().toString().split(" - ");
                    idAnimal = Integer.parseInt(partes[0]);
                    resultAnimal = animalController.selectAllFromAnimalById(idAnimal);
                }

                // pegar dono do animal e selecionar na combobox
                idDono = clienteAnimalObj.getDonoIdByAnimalId(idAnimal);
                cpfDono = clienteControllerObj.getClienteCpfById(idDono);

                cbDono.setEnabled(true);
                funcoesCB.populaComboBoxSelecionandoDono(cliente, cbDono, cpfDono);

                try {

                    if (resultAnimal != null) {
                        txtNome.setText(resultAnimal.getString("nome"));
                        txtEspecie.setText(resultAnimal.getString("especie"));
                        txtRaca.setText(resultAnimal.getString("raca"));
                        spnIdade.setValue(resultAnimal.getInt("idade"));
                    }
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnForm = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblEspecie = new javax.swing.JLabel();
        lblRaca = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        lblDono = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEspecie = new javax.swing.JTextField();
        txtRaca = new javax.swing.JTextField();
        cbDono = new org.jdesktop.swingx.JXComboBox();
        spnIdade = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        btnAddDono = new javax.swing.JButton();
        btnRefreshDono = new javax.swing.JButton();
        btnCadastrar = new customSwingComponents.JButtonCadastrar();
        lblSelectAnimal = new javax.swing.JLabel();
        cbSelectAnimal = new org.jdesktop.swingx.JXComboBox();

        setClosable(true);
        setTitle("Clínica Veterinária - Editar Animal");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/heart.png"))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/heart_add.png"))); // NOI18N
        lblTitulo.setText("Editar Animal");

        javax.swing.GroupLayout pnTituloLayout = new javax.swing.GroupLayout(pnTitulo);
        pnTitulo.setLayout(pnTituloLayout);
        pnTituloLayout.setHorizontalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(167, 167, 167))
        );
        pnTituloLayout.setVerticalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTituloLayout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(lblTitulo))
        );

        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNome.setText("Nome:");

        lblEspecie.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEspecie.setText("Espécie:");

        lblRaca.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRaca.setText("Raça:");

        lblIdade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdade.setText("Idade:");

        lblDono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDono.setText("Dono:");

        txtNome.setEnabled(false);

        txtEspecie.setEnabled(false);

        txtRaca.setEnabled(false);

        cbDono.setEnabled(false);

        spnIdade.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        spnIdade.setEnabled(false);

        jLabel1.setText("anos");

        btnAddDono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        btnAddDono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDonoActionPerformed(evt);
            }
        });

        btnRefreshDono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow_refresh.png"))); // NOI18N
        btnRefreshDono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshDonoActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Salvar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        lblSelectAnimal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSelectAnimal.setText("Selecione o animal:");

        cbSelectAnimal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSelectAnimalItemStateChanged(evt);
            }
        });
        cbSelectAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSelectAnimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnFormLayout = new javax.swing.GroupLayout(pnForm);
        pnForm.setLayout(pnFormLayout);
        pnFormLayout.setHorizontalGroup(
            pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFormLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNome, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEspecie, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRaca, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIdade, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDono, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSelectAnimal, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbSelectAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEspecie)
                    .addComponent(cbDono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRaca, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnFormLayout.createSequentialGroup()
                        .addComponent(spnIdade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addGroup(pnFormLayout.createSequentialGroup()
                        .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnFormLayout.createSequentialGroup()
                                .addComponent(btnAddDono, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRefreshDono, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(73, 73, 73))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFormLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );
        pnFormLayout.setVerticalGroup(
            pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFormLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSelectAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelectAnimal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEspecie)
                    .addComponent(txtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRaca)
                    .addComponent(txtRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdade)
                    .addComponent(spnIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDono)
                    .addComponent(cbDono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddDono)
                    .addComponent(btnRefreshDono))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtNome.setDocument( new LimitNumberCharacters(50) );
        txtEspecie.setDocument( new LimitNumberCharacters(50) );
        txtRaca.setDocument( new LimitNumberCharacters(50) );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(pnForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddDonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDonoActionPerformed
        // TODO add your handling code here:
        CadastrarCliente cadClienteView = new CadastrarCliente();
        jDesktopPane1.add(cadClienteView); // consigo adicionar no painel que veio por parametro da home, ou seja essa view aparece no painel da home
        cadClienteView.setVisible(true);
    }//GEN-LAST:event_btnAddDonoActionPerformed

    private void btnRefreshDonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshDonoActionPerformed
        // TODO add your handling code here:
        funcoesCB.populaComboBox(cliente, cbDono);
    }//GEN-LAST:event_btnRefreshDonoActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        AnimalController controller = new AnimalController();
        Funcoes funcoes = new Funcoes();
        FuncoesComboBox funcoesCb = new FuncoesComboBox();

        String nome = txtNome.getText();
        String raca = txtRaca.getText();
        String especie = txtEspecie.getText();
        int idade = (Integer) spnIdade.getValue();
        String cpfDono = cbDono.getSelectedItem().toString().split(" - ")[1];
        int idDono = cliente.selectIdFromClienteByCpf(cpfDono);

        animal = new Animal(idAnimal, nome, especie, raca, idade);

        if (controller.editarAnimal(animal, idDono)) {
            cbSelectAnimal.removeActionListener(cbSelectAnimal.getActionListeners()[0]);

            funcoesCb.populaComboBox(cliente, cbDono);
            funcoes.resetFields(pnForm);
            funcoes.disableFields(pnForm);
            cbDono.setEnabled(false);
            funcoesCB.populaComboBoxAnimalComId(animal, cbSelectAnimal);

            cbSelectAnimal.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {

                    for (Component c : pnForm.getComponents()) {
                        if (c instanceof JTextField || c instanceof JSpinner || c instanceof JXComboBox) {
                            c.setEnabled(true);
                        }
                    }

                    if (cbSelectAnimal.getSelectedItem() != null) {
                        String partes[] = cbSelectAnimal.getSelectedItem().toString().split(" - ");

                        if (!partes[0].isEmpty()) {
                            idAnimal = Integer.parseInt(partes[0]);
                        }

                        if (partes.length != 1) {
                            resultAnimal = controller.selectAllFromAnimalById(idAnimal);
                        }
                    }

                    // pegar dono do animal e selecionar na combobox
                    int idDonoPopula;
                    String cpfDonoPopula;
                    idDonoPopula = clienteAnimalObj.getDonoIdByAnimalId(idAnimal);
                    cpfDonoPopula = clienteControllerObj.getClienteCpfById(idDonoPopula);

                    cbDono.setEnabled(true);
                    funcoesCB.populaComboBoxSelecionandoDono(cliente, cbDono, cpfDonoPopula);

                    try {

                        if (resultAnimal != null) {
                            txtNome.setText(resultAnimal.getString("nome"));
                            txtEspecie.setText(resultAnimal.getString("especie"));
                            txtRaca.setText(resultAnimal.getString("raca"));
                            spnIdade.setValue(resultAnimal.getInt("idade"));

                            idAnimal = resultAnimal.getInt("id");
                        }
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                }
            });
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void cbSelectAnimalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSelectAnimalItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSelectAnimalItemStateChanged

    private void cbSelectAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSelectAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSelectAnimalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDono;
    private customSwingComponents.JButtonCadastrar btnCadastrar;
    private javax.swing.JButton btnRefreshDono;
    private org.jdesktop.swingx.JXComboBox cbDono;
    private org.jdesktop.swingx.JXComboBox cbSelectAnimal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDono;
    private javax.swing.JLabel lblEspecie;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRaca;
    private javax.swing.JLabel lblSelectAnimal;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnForm;
    private javax.swing.JPanel pnTitulo;
    private javax.swing.JSpinner spnIdade;
    private javax.swing.JTextField txtEspecie;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRaca;
    // End of variables declaration//GEN-END:variables
}
